# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# jekyll serve. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use theme or remote_theme
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "mint" # Changed to "mint" for a fresh, professional look

# Site Settings
locale                   : "en-US"
rtl                      : false # Default for left-to-right languages like English
title                    : "Sandra Marion Kam Tsemo"
title_separator          : " | "
subtitle                 : "PhD Candidate in Mathematical Modelling"
name                     : "Sandra Marion Kam Tsemo"
description              : "A PhD Candidate at Leibniz Centre for Tropical Marine Research (ZMT), specializing in mathematical modelling of marine ecosystems, with a focus on nitrogen fixation and ecological dynamics."
url                      : "https://sandrakt.github.io" # Your GitHub Pages URL
baseurl                  : "" # No subpath needed for GitHub Pages
repository               : "sandrakt/sandrakt.github.io" # Your GitHub repository
teaser                   : "/assets/images/teaser.jpg" # Add a teaser image later if desired
logo                     : "/assets/images/logo.png" # Add a logo image later if desired
masthead_title           : "Sandra Marion Kam Tsemo | Mathematical Modelling & Marine Ecology"
breadcrumbs              : true # Enable breadcrumbs for better navigation
words_per_minute         : 200
enable_copy_code_button  : true # Useful for code snippets in research posts
copyright                : "Sandra Marion Kam Tsemo"
copyright_url            : "https://sandrakt.github.io"
comments:
  provider               : false # Disable comments for now; enable later if needed
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : false
search                   : true # Enable search functionality
search_full_content      : true # Allow searching full content of posts
search_provider          : lunr # Default search provider
lunr:
  search_within_pages    : true

# SEO Related
google_site_verification :
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

# Social Sharing
twitter:
  username               : # Add your Twitter handle if applicable
facebook:
  username               : # Add your Facebook handle if applicable
  app_id                 :
  publisher              :
og_image                 : "/assets/images/og-image.jpg" # Add an Open Graph image later if desired
social:
  type                   : Person
  name                   : "Sandra Marion Kam Tsemo"
  links:
    - "https://github.com/sandraKT"
    - "mailto:sandra.tsemo@leibniz-zmt.de"

# Analytics
analytics:
  provider               : false # Enable Google Analytics later if desired

# Site Author
author:
  name             : "Sandra Marion Kam Tsemo"
  avatar           : "/assets/images/sandra-photo.jpg" # Add a professional photo to assets/images/
  bio              : "PhD Candidate at Leibniz Centre for Tropical Marine Research (ZMT), Bremen, Germany. Specializing in mathematical modelling of marine ecosystems, with a focus on nitrogen fixation, ecological dynamics, and sustainable resource management."
  location         : "Bremen, Germany"
  email            : "sandra.tsemo@leibniz-zmt.de"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:sandra.tsemo@leibniz-zmt.de"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sandraKT"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/sandra-marion-kam-tsemo" # Add your LinkedIn URL if available

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sandraKT"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:sandra.tsemo@leibniz-zmt.de"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Europe/Berlin # Set to your timezone

# Pagination with jekyll-paginate
paginate: 5
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
